FROM glassfish/server:4.1.1
# See: https://hub.docker.com/r/glassfish/server/~/dockerfile/
# See: https://github.com/glassfish/docker/tree/master/4.1.1


MAINTAINER Ioannis Noukakis <ioannis.noukakis@heig-vd.ch>


ADD projet-1.0-SNAPSHOT.war /glassfish4/glassfish/domains/domain1/autodeploy/
