version: '2'
services:
    mysql:
        build: ../images/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 1234
   
           
    glassfish:
        build: ../images/glassfish
        ports:
            - "8080:8080"
            - "4848:4848"
            
    phpmyadmin:
        build: ../images/phpmyadmin
        environment:
            MYSQL_ROOT_PASSWORD: 1234
        ports:
            - "6060:80"
        links:
            - mysql:db